### ISSUE TITLE
Freeze in multiplayer

### ISSUE THREAD

**Issue by kalou** [ForFunLabs/ElevenPublicBugsAndAsks#379]
Hi there,

During multiplayer game, the game would freeze  - I still have mic/audio and can talk to the other player but the image is not updated with head movements (and it feels very weird). I need to exit the game and restart it.

I possibly also notice moments where frames are dropped and it looks like it's going to crash but recovers.

I only play with the same friend, and it is always happening on my end - never to him, even though we both have the same setup - (Eleven 1.387, Oculus quest 904120.17180.0, latest OS version)

I don't think I ever observed this playing against the AI.

How can I record more of this and send you a trace? It is random but happens every time we play.

[Edit1: found [this reddit thread](https://www.reddit.com/r/OculusQuest/comments/fdqc1l/eleven_table_tennis_crashing/)]
[Edit2: found the below in the log, let me know if I can do more]

```
10-04 20:51:01.248  2969  2969 E AndroidRuntime: FATAL EXCEPTION: main
10-04 20:51:01.248  2969  2969 E AndroidRuntime: Process: quest.eleven.forfunlabs, PID: 2969
10-04 20:51:01.248  2969  2969 E AndroidRuntime: java.lang.Error: FATAL EXCEPTION [main]
10-04 20:51:01.248  2969  2969 E AndroidRuntime: Unity version     : 2019.3.4f1
10-04 20:51:01.248  2969  2969 E AndroidRuntime: Device model      : Oculus Quest
10-04 20:51:01.248  2969  2969 E AndroidRuntime: Device fingerprint: oculus/vr_monterey/monterey:7.1.1/NGI77B/904120.17180.0:user/release-keys
10-04 20:51:01.248  2969  2969 E AndroidRuntime:
10-04 20:51:01.248  2969  2969 E AndroidRuntime: Caused by: java.lang.Error: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
10-04 20:51:01.248  2969  2969 E AndroidRuntime: Version '2019.3.4f1 (4f139db2fdbd)', Build type 'Release', Scripting Backend 'il2cpp', CPU 'arm64-v8a'
10-04 20:51:01.248  2969  2969 E AndroidRuntime: Build fingerprint: 'oculus/vr_monterey/monterey:7.1.1/NGI77B/904120.17180.0:user/release-keys'
10-04 20:51:01.248  2969  2969 E AndroidRuntime: Revision: '0'
10-04 20:51:01.248  2969  2969 E AndroidRuntime: ABI: 'arm64'
10-04 20:51:01.248  2969  2969 E AndroidRuntime: Timestamp: 2020-10-04 20:50:53-0700
10-04 20:51:01.248  2969  2969 E AndroidRuntime: pid: 2969, tid: 3011, name: Thread-3  >>> quest.eleven.forfunlabs <<<
10-04 20:51:01.248  2969  2969 E AndroidRuntime: uid: 10085
10-04 20:51:01.248  2969  2969 E AndroidRuntime: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x9b64f4d490
10-04 20:51:01.248  2969  2969 E AndroidRuntime:     x0  0000007f465feac0  x1  0000007f60620298  x2  000000000000000f  x3  0000000000000000
10-04 20:51:01.248  2969  2969 E AndroidRuntime:     x4  8080800000000080  x5  0000007f49540c00  x6  800c54497f808080  x7  fefeff7e48530aff
10-04 20:51:01.248  2969  2969 E AndroidRuntime:     x8  0000000000000000  x9  0000009b64f4d490  x10 0000000000000001  x11 0000000000000000
10-04 20:51:01.248  2969  2969 E AndroidRuntime:     x12 0000000000000bc3  x13 0000000000000bc3  x14 09101e2a7795bc55  x15 0000000000000000
10-04 20:51:01.248  2969  2969 E AndroidRuntime:     x16 0000007f61ae90c0  x17 0000007f7f1402dc  x18 000000000000ffff  x19 0000007f465fe860
10-04 20:51:01.248  2969  2969 E AndroidRuntime:     x20 0000000000000068  x21 00000000465fefc0  x22 0000007f61b6bf70  x23 0000007ecdfb6e90
10-04 20:51:01.248  2969  2969 E AndroidRuntime:     x24 0000007f61798a9d  x25 00000000ffffffff  x26 0000007f465fe850  x27 0000007eb53198c0
10-04 20:51:01.248  2969  2969 E AndroidRuntime:     x28 0000000000000000  x29 0000007f465fefc0
10-04 20:51:01.248  2969  2969 E AndroidRuntime:     sp  0000007f465fe850  lr  0000007f60ded664  pc  0000007f60ded678
10-04 20:51:01.248  2969  2969 E AndroidRuntime:
10-04 20:51:01.248  2969  2969 E AndroidRuntime: backtrace:
10-04 20:51:01.248  2969  2969 E AndroidRuntime:       #00 pc 0000000000412678  /data/app/quest.eleven.forfunlabs-1/lib/arm64/libunity.so (BuildId: 0247c6c5cb8a15dc3ebc20d5fe4869b6453a5f59)
10-04 20:51:01.248  2969  2969 E AndroidRuntime:       #01 pc 00000000004248d0  /data/app/quest.eleven.forfunlabs-1/lib/arm64/libunity.so (BuildId: 0247c6c5cb8a15dc3ebc20d5fe4869b6453a5f59)
10-04 20:51:01.248  2969  2969 E AndroidRuntime:       #02 pc 0000000000581e40  /data/app/quest.eleven.forfunlabs-1/lib/arm64/libunity.so (BuildId: 0247c6c5cb8a15dc3ebc20d5fe4869b6453a5f59)
10-04 20:51:01.248  2969  2969 E AndroidRuntime:       #03 pc 000000000089c238  /data/app/quest.eleven.forfunlabs-1/lib/arm64/libunity.so (BuildId: 0247c6c5cb8a15dc3ebc20d5fe4869b6453a5f59)
10-04 20:51:01.248  2969  2969 E AndroidRuntime:       #04 pc 00000000008b3968  /data/app/quest.eleven.forfunlabs-1/lib/arm64/libunity.so (BuildId: 0247c6c5cb8a15dc3ebc20d5fe4869b6453a5f59)
10-04 20:51:01.248  2969  2969 E AndroidRuntime:       #05 pc 00000000008b9b88  /data/app/quest.eleven.forfunlabs-1/lib/arm64/libunity.so (BuildId: 0247c6c5cb8a15dc3ebc20d5fe4869b6453a5f59)
10-04 20:51:01.248  2969  2969 E AndroidRuntime:       #06 pc 00000000008b1040  /data/app/quest.eleven.forfunlabs-1/lib/arm64/libunity.so (BuildId: 0247c6c5cb8a15dc3ebc20d5fe4869b6453a5f59)
10-04 20:51:01.248  2969  2969 E AndroidRuntime:       #07 pc 0000000000314478  /data/app/quest.eleven.forfunlabs-1/lib/arm64/libunity.so (BuildId: 0247c6c5cb8a15dc3ebc20d5fe4869b6453a5f59)
10-04 20:51:01.248  2969  2969 E AndroidRuntime:       #08 pc 0000000000076454  /system/lib64/libc.so (__pthread_start(void*)+204) (BuildId: 0d82b5085cc8358649be6ff5d14ed691)
10-04 20:51:01.248  2969  2969 E AndroidRuntime:       #09 pc 000000000001e204  /system/lib64/libc.so (__start_thread+16) (BuildId: 0d82b5085cc8358649be6ff5d14ed691)
10-04 20:51:01.248  2969  2969 E AndroidRuntime:
10-04 20:51:01.248  2969  2969 E AndroidRuntime: 	at libunity.0x412678(Native Method)
10-04 20:51:01.248  2969  2969 E AndroidRuntime: 	at libunity.0x4248d0(Native Method)
10-04 20:51:01.248  2969  2969 E AndroidRuntime: 	at libunity.0x581e40(Native Method)
10-04 20:51:01.248  2969  2969 E AndroidRuntime: 	at libunity.0x89c238(Native Method)
10-04 20:51:01.248  2969  2969 E AndroidRuntime: 	at libunity.0x8b3968(Native Method)
10-04 20:51:01.248  2969  2969 E AndroidRuntime: 	at libunity.0x8b9b88(Native Method)
10-04 20:51:01.248  2969  2969 E AndroidRuntime: 	at libunity.0x8b1040(Native Method)
10-04 20:51:01.248  2969  2969 E AndroidRuntime: 	at libunity.0x314478(Native Method)
10-04 20:51:01.248  2969  2969 E AndroidRuntime: 	at libc.__pthread_start(void*)(__pthread_start:204)
10-04 20:51:01.248  2969  2969 E AndroidRuntime: 	at libc.__start_thread(__start_thread:16)
```

**Comment by kalou** [comment]
Now that I think about it, it might be an unrelated crash exiting the game.

**Comment by dukeoflegs** [comment]
Closing, no longer an issue.
